version: '3.0'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=sqs,s3

    ports:
      - '4566-4597:4566-4597'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"